### ISSUE TITLE
Unit Testing -> TypeError: Cannot destructure property 'UserManager' of 'oidcClient' as it is undefined.

### ISSUE THREAD

**Issue by pdelap26** [dopry/svelte-oidc#16]
Hello everyone :) 

I'm trying to add testing to our app, starting with our Login component which includes svelte-oidc and i receive this error whenever i'm testing.

TypeError: Cannot destructure property 'UserManager' of 'oidcClient' as it is undefined

I solved it on my side by modifying the OidcContext.svelte line 4 `import * as oidcClient from 'oidc-client'`and line 123 `const userManager = new oidcClient.UserManager(settings)`.

But i don't believe it is the best way to fix it. It may also be related to jest/ts-jest for all i know.

Just in case, here is my jest.config : 

```
const sveltePreprocess = require('svelte-preprocess')
module.exports = {
  verbose: true,
  transform: {
    '^.+\\.svelte$': [
      'svelte-jester',
      [
        sveltePreprocess(),
      ]
    ],
    '^.+\\.ts$': 'ts-jest'
  },
  testPathIgnorePatterns: [
    '<rootDir>/node_modules/',
    '<rootDir>/dist/'
  ],
  moduleFileExtensions: [
    'js',
    'ts',
    'svelte'
  ],
  setupFilesAfterEnv: ['@testing-library/jest-dom/extend-expect'],
  transformIgnorePatterns: [
    // mandatory for non compiled ES6 dependencies
    '^.+\\.js$'
  ],
}
```

Any thoughts ? My team is pretty new at Svelte development so we may also just be lousy svelte developers haha

It is the first time i submit that kind of issue so feel free to tell me if i forgot anything 😃

**Comment by matmunn** [comment]
Try pulling the latest code from master. It looks like there's a fix there for that that's not published yet

**Comment by pdelap26** [comment]
Oh just read the source code and it does seem to be solved, should we let the issue open until it is merged and made public ?

Thank you for your answer ! 😄  I was trying everything with my jest conf haha

**Comment by mitjakukovec** [comment]
@dopry is there a planned release to have the latest changes from main in the official build? Thanks!

**Comment by dopry** [comment]
@mitjakukovec what version of @dopry/svelte-oidc are you using? 1.1.0 was published 10 months ago and should have the fixes to the destructuring issues.

**Comment by mitjakukovec** [comment]
I'm sorry for any confusion. To clarify, I don't have any issues with destructuring. My question is about the next official release that will include all updates implemented since the last official release, which was 10 months ago.

**Comment by dopry** [comment]
@mitjakukovec 
1. do not hijack unrelated issues for unrelated questions, open a new issue in the future.
2. there have been no major changes in the last 10 months to release besides updates to build dependencies. there is nothing that warrants a release.
