### ISSUE TITLE
OpenID Provider Issuer Discovery should be optional

### ISSUE THREAD

**Issue by petershaw** [dopry/svelte-oidc#34]
I tested the lib against a server that do not serve a .well-known issuer discovery information. 
The (Specs)[https://openid.net/specs/openid-connect-discovery-1_0.html#IssuerDiscovery] says, that `Issuer discovery is OPTIONAL`

I set all links to /autorize and /token in the metadata object
```typescript
  const metadata = {
      end_session_endpoint: `https://...`,
      issuer: 'https://....',
      token_endpoint: 'https://...',
      authorization_endpoint: 'https://....',
      userinfo_endpoint: 'https://....',
  };
  
svelte-oicd complains a 404 on the .well-known/openid-configuration endpoint and stops working. 

Did I miss an undocumented option?

**Comment by dopry** [comment]
svelte-oidc is just a thin wrapper around [oidc-client](https://github.com/IdentityModel/oidc-client-js). there isn't anything in svelte-oidc itself that validates those settings. you'll have to check there to figure out whether it is possible and how to configure it without a discovery endopint.

**Comment by dopry** [comment]
Did you figure out a way to make it work without providing the discovery end point?
