### ISSUE TITLE
Docker build fail

### ISSUE THREAD

**Issue by Milos5611** [dopry/svelte-oidc#5]
Trying to build a docker image of my svelte app.
Throwing error
```
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/dopry/oidc-client-js.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
```

**Comment by dopry** [comment]
This looks like an issue with npm, your network, or your package.json. I'd
suggest asking for help in an npm forum.

**Comment by Milos5611** [comment]
@dopry checked a number of times since yesterday.
`npm install` do the job for every module in package JSON except for this one.
It's still failing and at the end of development, I can't build a project and deploy.

**Comment by dopry** [comment]
Is git installed on your build agent? The error indicates npm couldn't find
git to download the oidc-client-js module.

**Comment by Milos5611** [comment]
@dopry why is this ticket closed?
I am telling you that all packages are fetched ok from git except this one. 
This is a bug and has to be investigated.
