### ISSUE TITLE
How to use `login()`?

### ISSUE THREAD

**Issue by florian-forestier** [dopry/svelte-oidc#52]
Hi,

First of all, thanks to all the people who worked (or still working) on this project, which is a great wrapper around oidc-client. I managed without any complication to configure this library to log-in with my OIDC provider by clicking on the Login button.

However, I'm struggling with the `login` function: I want to automatically redirect an unauthenticated user to my OIDC provider. My idea was to subscribe to `authError`, and trigger the `login` function. The problem is that `login` takes at least one parameter, which is an `oidcPromise`. How can I retrieve/create this `oidcPromise`?

I'm using the npm package.

Thank you in advance, have a good day!

**Comment by dopry** [comment]
Look at the source for the login button, 

https://github.com/dopry/svelte-oidc/blob/master/src/components/LoginButton.svelte
