### ISSUE TITLE
OIDC Object is undefined in login()

### ISSUE THREAD

**Issue by ericschmar** [dopry/svelte-oidc#6]
I am configuring this to use a private OIDC provider for an Auth Code flow. It has a well known configuration endpoint, etc. 

I can verify that the oidc object is properly created inside the `handleOnMount()`, however, when I click the Login button, the context returns undefined. Then `await oidc.signinRedirect({ redirect_uri, appState });` throws an exception as it is attempting to call a function on undefined. 

I am able to run the showcase project in this repo fine. The only difference I can find is that the oidc object in this sample repo populates the metadata object with all the various properties. However, the object I see in `handleOnMount()` in my repo has the metadata as totally empty still. I'm wondering if there is a known issue with the UserManager library that requires a full metadata object, since looking through this repo, it looks like it relies on that library for all that functionality.

**Comment by StevenSavold** [comment]
I am having similar issues, was there a solution to this problem?

**Comment by StevenSavold** [comment]
For anyone who might stumble across this in the future, I was able to solve the issue by using the <LoginButton> element which seems provided in the library. The documentation seems out of date at the moment, and the main example in the readme is calling login() wrong. Looking at [JackDra's Fork](https://github.com/JackDra/svelte-oidc) of the repo has an updated readme which works with the root repo. Hope this helps
